//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Quantum.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_QuantumTYPE                 129
#define IDD_PARTICLE_MOVEMENT           130
#define IDD_PARTICLE_COLOR              131
#define IDD_PARTICLE_PROPERTIES         132
#define IDD_VECTOR_PROPERTIES           134
#define IDD_WAVE_PROPERTIES             135
#define IDD_PARTICLE_APPEARANCE         136
#define IDD_VIEW_OPTIONS                137
#define IDD_PARTICLE_SYSTEMS            138
#define IDI_PARTICLE                    139
#define IDI_EMITTER                     140
#define IDI_SYSTEM                      141
#define IDR_MENU1                       142
#define IDD_OUTPUT_WINDOW               143
#define IDD_DIALOG1                     145
#define IDD_STATS                       145
#define IDD_PARTICLE_PHYSICS            146
#define IDC_VEL_X_SLIDER                1000
#define IDC_VEL_X_EDIT                  1001
#define IDC_ACC_X_SLIDER                1002
#define IDC_VEL_X_LABEL                 1003
#define IDC_BUTTON1                     1005
#define IDC_WIND_OPTIONS                1005
#define IDC_APPLY                       1005
#define IDC_BROWSE_TEXTURE              1005
#define IDAPPLY                         1005
#define IDC_NEW_SYSTEM                  1005
#define IDC_RESET_CURRENT_EMITTER       1005
#define IDC_VEL_RAD_WAVE_PARAMS         1006
#define IDC_GRAVITY_OPTIONS             1006
#define IDC_VEL_RAD_WAVE                1007
#define IDC_VEL_ANG_WAVE                1008
#define IDC_VEL_THETA_WAVE              1008
#define IDC_VEL_Y_SLIDER                1009
#define IDC_COLOR_RED_SLIDER            1010
#define IDC_VEL_Z_SLIDER                1010
#define IDC_VEL_Y_EDIT                  1011
#define IDC_COLOR_RED_EDIT              1012
#define IDC_VEL_Z_EDIT                  1012
#define IDC_VEL_Y_LABEL                 1013
#define IDC_COLOR_RED_LABEL             1014
#define IDC_VEL_Z_LABEL                 1014
#define IDC_VEL_RAD_SLIDER              1015
#define IDC_COLOR_GREEN_SLIDER          1016
#define IDC_VEL_PHI_WAVE                1016
#define IDC_VEL_RAD_EDIT                1017
#define IDC_COLOR_GREEN_EDIT            1018
#define IDC_GRAVITY_OPTIONS2            1018
#define IDC_VEL_RAD_LABEL               1019
#define IDC_COLOR_GREEN_LABEL           1020
#define IDC_PROPS_EXPLOSION             1021
#define IDC_VEL_ANG_SLIDER              1022
#define IDC_VEL_THETA_SLIDER            1022
#define IDC_COLOR_BLUE_SLIDER           1023
#define IDC_VEL_PHI_SLIDER              1023
#define IDC_PROPS_MAX_PARTICLES_LABEL   1024
#define IDC_VEL_ANG_EDIT                1025
#define IDC_VEL_THETA_EDIT              1025
#define IDC_COLOR_BLUE_EDIT             1026
#define IDC_VEL_PHI_EDIT                1026
#define IDC_PROPS_MAX_PARTICLES_SLIDER  1027
#define IDC_VEL_ANG_LABEL               1028
#define IDC_VEL_THETA_LABEL             1028
#define IDC_COLOR_BLUE_LABEL            1029
#define IDC_VEL_PHI_LABEL               1029
#define IDC_PROPS_MAX_PARTICLES_EDIT    1030
#define IDC_COLOR_ALPHA_SLIDER          1031
#define IDC_PROPS_EMIT_RATE_SLIDER      1032
#define IDC_VEL_ANG_WAVE_PARAMS         1033
#define IDC_VEL_THETA_WAVE_PARAMS       1033
#define IDC_COLOR_ALPHA_EDIT            1034
#define IDC_VEL_PHI_WAVE_PARAMS         1034
#define IDC_PROPS_EMIT_RATE_EDIT        1035
#define IDC_VEL_POLAR_PICKUP_RANGE_SLIDER 1036
#define IDC_COLOR_ALPHA_LABEL           1037
#define IDC_PROPS_EMIT_RATE_LABEL       1038
#define IDC_VEL_POLAR_PICKUP_RANGE_EDIT 1039
#define IDC_DECAY_RED_SLIDER            1040
#define IDC_PROPS_MIN_LIFE_SLIDER       1041
#define IDC_ACC_X_EDIT                  1042
#define IDC_DECAY_RED_EDIT              1043
#define IDC_PROPS_MIN_LIFE_EDIT         1044
#define IDC_ACC_X_LABEL                 1045
#define IDC_DECAY_RED_LABEL             1046
#define IDC_PROPS_MIN_LIFE_LABEL        1047
#define IDC_ACC_Y_SLIDER                1048
#define IDC_DECAY_GREEN_SLIDER          1049
#define IDC_ACC_Z_SLIDER                1049
#define IDC_PROPS_MAX_LIFE_SLIDER       1050
#define IDC_ACC_Y_EDIT                  1051
#define IDC_DECAY_GREEN_EDIT            1052
#define IDC_ACC_Z_EDIT                  1052
#define IDC_PROPS_MAX_LIFE_EDIT         1053
#define IDC_ACC_Y_LABEL                 1054
#define IDC_DECAY_GREEN_LABEL           1055
#define IDC_ACC_Z_LABEL                 1055
#define IDC_PROPS_MAX_LIFE_LABEL        1056
#define IDC_ACC_RAD_SLIDER              1057
#define IDC_DECAY_BLUE_SLIDER           1058
#define IDC_PROPS_SPAWN_SHAPE           1059
#define IDC_ACC_RAD_EDIT                1060
#define IDC_DECAY_BLUE_EDIT             1061
#define IDC_ACC_RAD_LABEL               1062
#define IDC_DECAY_BLUE_LABEL            1063
#define IDC_ACC_ANG_SLIDER              1064
#define IDC_DECAY_ALPHA_SLIDER          1065
#define IDC_ACC_ANG_SLIDER2             1065
#define IDC_PROPS_SIZE_SLIDER           1066
#define IDC_ACC_ANG_EDIT                1067
#define IDC_DECAY_ALPHA_EDIT            1068
#define IDC_ACC_ANG_EDIT2               1068
#define IDC_PROPS_SIZE_EDIT             1069
#define IDC_ACC_ANG_LABEL               1070
#define IDC_ACC_THETA_LABEL             1070
#define IDC_DECAY_ALPHA_LABEL           1071
#define IDC_ACC_THETA_LABEL2            1071
#define IDC_PROPS_SIZE_LABEL            1072
#define IDC_PROPS_MIN_SPAWN_ANGLE_SLIDER 1073
#define IDC_PROPS_MIN_SPAWN_ANGLE_THETA_SLIDER 1073
#define IDC_PROPS_MIN_SPAWN_ANGLE_EDIT  1074
#define IDC_PROPS_MIN_SPAWN_ANGLE_THETA_EDIT 1074
#define IDC_PROPS_MIN_SPAWN_ANGLE_LABEL 1075
#define IDC_PROPS_MIN_SPAWN_ANGLE_THETA_LABEL 1075
#define IDC_PROPS_MAX_SPAWN_ANGLE_SLIDER 1076
#define IDC_PROPS_MAX_SPAWN_ANGLE_THETA_SLIDER 1076
#define IDC_PROPS_MAX_SPAWN_ANGLE_EDIT  1077
#define IDC_PROPS_MAX_SPAWN_ANGLE_THETA_EDIT 1077
#define IDC_PROPS_MAX_SPAWN_ANGLE_LABEL 1078
#define IDC_PROPS_MAX_SPAWN_ANGLE_THETA_LABEL 1078
#define IDC_EMITTER_ACTIVE              1079
#define IDC_APPLY_WIND                  1080
#define IDC_PROPS_MIN_SPAWN_ANGLE_PHI_SLIDER 1080
#define IDC_APPLY_GRAVITY               1081
#define IDC_PROPS_MIN_SPAWN_ANGLE_PHI_EDIT 1081
#define IDC_PROPS_EMIT_RADIUS_SLIDER    1082
#define IDC_COLOR_BLEND                 1082
#define IDC_PROPS_EMIT_RADIUS_EDIT      1083
#define IDC_FREQ_EDIT                   1084
#define IDC_PROPS_MAX_SPAWN_ANGLE_PHI_SLIDER 1084
#define IDC_BASE_EDIT                   1085
#define IDC_COLLISIONS                  1085
#define IDC_BASE_EDIT2                  1086
#define IDC_RESET_ALL                   1086
#define IDC_TEXTURE_PATH                1087
#define IDC_PROPS_MAX_SPAWN_ANGLE_EDIT2 1087
#define IDC_PROPS_MAX_SPAWN_ANGLE_PHI_EDIT 1087
#define IDC_RANDOMIZE_COLOR             1088
#define IDC_PROPS_MIN_SPAWN_ANGLE_PHI_LABEL 1088
#define IDC_EYE_POINT_X                 1089
#define IDC_PROPS_MAX_SPAWN_ANGLE_PHI_LABEL 1089
#define IDC_DEFAULTS                    1090
#define IDC_CLIP_NEAR                   1091
#define IDC_EYE_POINT_Y                 1092
#define IDC_APPLY_TEXTURE               1092
#define IDC_EYE_POINT_Z                 1093
#define IDC_LOOKAT_POINT_X              1094
#define IDC_CURRENT_TEXTURE_PATH        1094
#define IDC_LOOKAT_POINT_Y              1095
#define IDC_RECENT_TEXTURES             1095
#define IDC_LOOKAT_POINT_Z              1096
#define IDC_ADD_TEXTURE                 1096
#define IDC_UP_VECTOR_X                 1097
#define IDC_TEXTURE_PREVIEW             1097
#define IDC_UP_VECTOR_Y                 1098
#define IDC_PARTICLE_SYSTEM_TREE        1098
#define IDC_UP_VECTOR_Z                 1099
#define IDC_DELETE_ALL                  1099
#define IDC_CLIP_FAR                    1100
#define IDC_CONSOLE_OUTPUT              1100
#define IDC_CONSOLE_INPUT               1101
#define IDC_EMITTER_VISIBLE             1104
#define IDC_EMITTER_PAUSED              1105
#define IDC_DELETE_SEL_TEX              1107
#define IDC_APPLY_SEL_TEX               1108
#define IDC_X                           1109
#define IDC_Y                           1110
#define IDC_EMITTER_COUNT               1110
#define IDC_Z                           1111
#define IDC_NUM_ACTIVE                  1111
#define IDC_W                           1112
#define IDC_NUM_VISIBLE                 1112
#define IDC_NUM_RENDERLISTS             1113
#define IDC_PROC_TIME                   1114
#define IDC_MEM_USAGE                   1115
#define IDC_NUM_PARTICLES               1116
#define IDC_ACTIVE_COLOR_MODE           1117
#define IDC_RANDOM_SEED                 1118
#define IDC_COLOR_MULTIPLIER            1119
#define IDC_RANDOMIZE_MASS              1120
#define IDC_TIME_MULTIPLIER             1121
#define IDC_APPLY_EMFORCE               1122
#define IDC_RANDOM_CHARGE               1123
#define IDC_CLEAR_HISTORY               1124
#define IDC_GRAPH_HISTORY               1125
#define IDC_GRAPH_IDS                   1126
#define IDC_SPLIT1                      1127
#define IDC_COMBO1                      1128
#define IDC_SPAWN_DIST                  1129
#define ID_FILE_OPENIMAGE               32771
#define ID_FILE_OPEN32772               32772
#define ID_OPEN_IMAGE                   32773
#define ID_VIEW_GENERALPROPERTIES       32776
#define ID_VIEW_MOVEMENTOPTIONS         32777
#define ID_VIEW_GENERALOPTIONS          32778
#define ID_VIEW_COLOROPTIONS            32779
#define ID_VIEW_APPEARANCEOPTIONS       32780
#define ID_SYSTEMSMENU_DELETE           32781
#define ID_FILE_SAVESTATE               32782
#define ID_FILE_LOADSTATE               32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1130
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
